apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "msnelling/renovate",
        "msnelling/argocd-bootstrap",
        "msnelling/argocd-db3000",
        "msnelling/gitops-teslamate",
        "msnelling/dns"
      ],
      "timezone": "Europe/London",
      "labels": ["renovate"],
      "automerge": false,
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch"], 
          "automerge": true
        }
      ]
    }
