apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:37.425.1
              env:
                - name: LOG_LEVEL
                  value: info
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.json
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: ssh-key-volume
                  readOnly: true
                  mountPath: /home/ubuntu/.ssh
                - name: work-volume
                  mountPath: /tmp/renovate/
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: ssh-key-volume
              secret:
                secretName: ssh-key-secret
            - name: work-volume
              emptyDir: {}
