---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-key-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ssh-key-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        config: "{{ .config }}"
        id_rsa: "{{ .privateKey }}"
        id_rsa.pub: "{{ .publicKey }}"
  data:
    - secretKey: config
      remoteRef:
        key: secret/renovate/ssh
        property: config
    - secretKey: privateKey
      remoteRef:
        key: secret/renovate/ssh
        property: privateKey
    - secretKey: publicKey
      remoteRef:
        key: secret/renovate/ssh
        property: publicKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: renovate-env
    template:
      engineVersion: v2
      type: Opaque
      data:
        GITHUB_COM_TOKEN: "{{ .githubToken }}"     # GitHub PAT to retrieve changelog
        RENOVATE_AUTODISCOVER: "{{ .renovateAutodiscover }}"
        RENOVATE_ENDPOINT: "{{ .renovateEndpoint }}"
        RENOVATE_GIT_AUTHOR: "{{ .renovateGitAuthor }}"
        RENOVATE_PLATFORM: "{{ .renovatePlatform }}"
        RENOVATE_TOKEN: "{{ .renovateToken }}" # your github enterprise renovate user token
  data:
    - secretKey: githubToken
      remoteRef:
        key: secret/renovate/github
        property: token
    - secretKey: renovateAutodiscover
      remoteRef:
        key: secret/renovate/renovate
        property: autodiscover
    - secretKey: renovateEndpoint
      remoteRef:
        key: secret/renovate/renovate
        property: endpoint
    - secretKey: renovateGitAuthor
      remoteRef:
        key: secret/renovate/renovate
        property: author
    - secretKey: renovatePlatform
      remoteRef:
        key: secret/renovate/renovate
        property: platform
    - secretKey: renovateToken
      remoteRef:
        key: secret/renovate/github
        property: token

