apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: renovate
resources:
  - secret-store.yaml
  - external-secrets.yaml
  - config.yaml
  - cronjob.yaml