apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth2
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-github-oauth2
    template:
      type: Opaque
      data:
        provider: |
          name: github
          label: GitHub
          app_id: {{ .appId}}
          app_secret: {{ .appSecret }}
          args:
            scope: user:email
  data:
    - secretKey: appId
      remoteRef:
        key: secret/github/oauth/gitlab
        property: clientId
    - secretKey: appSecret
      remoteRef:
        key: secret/github/oauth/gitlab
        property: clientSecret
