---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-gitlab
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gitlab-gitaly
  capacity:
    storage: 20Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: gitlab-gitaly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gitlab-gitaly
  resources:
    requests:
      storage: 20Gi
  volumeName: gitlab-gitaly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-gitlab-redis-master-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gitlab
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitlab-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gitlab
  resources:
    requests:
      storage: 5Gi
