apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth2
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-github-oauth2
    template:
      type: Opaque
      data:
        provider: |
          [default]

          # Setup endpoint
          host_base = s3.xmple.io:9000
          host_bucket = s3.xmple.io:9000
          bucket_location = home
          use_https = True

          # Setup access keys
          access_key = {{ .accessKey }}
          secret_key = {{ .secretKey }}

          # Enable S3 v4 signature APIs
          signature_v2 = False
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/s3/minio/root
        property: access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/s3/minio/root
        property: secret_key
