---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-root-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-root-password
    template:
      type: Opaque
      data:
        password: {{ .password }}
        postgresql_password: {{ .postgresqlPassword }}
        postgresql_postgres_password: {{ .postgresqlPostgresPassword }}
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/install
        property: default_root_password
    - secretKey: postgresqlPassword
      remoteRef:
        key: secret/gitlab/install
        property: postgresql_password
    - secretKey: postgresqlPostgresPassword
      remoteRef:
        key: secret/gitlab/install
        property: postgresql_postgres_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-postgresql-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-postgresql-password
    template:
      type: Opaque
      data:
        postgresql-password: {{ .postgresqlPassword }}
        postgresql-postgres-password: {{ .postgresqlPostgresPassword }}
  data:
    - secretKey: postgresqlPassword
      remoteRef:
        key: secret/gitlab/install
        property: postgresql_password
    - secretKey: postgresqlPostgresPassword
      remoteRef:
        key: secret/gitlab/install
        property: postgresql_postgres_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-runner-secret
    template:
      type: Opaque
      data:
        runner-registration-token: {{ .token }}
  data:
    - secretKey: token
      remoteRef:
        key: secret/gitlab/install
        property: runner_registration_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: smtp-password
    template:
      type: Opaque
      data:
        password: {{ .password }}
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/smtp
        property: password
