apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-gitlab
spec:
  blocks:
    - start: "10.1.1.52"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: gitlab
      io.kubernetes.service.name: gitlab-traefik
