apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-object-storage
    template:
      type: Opaque
      data:
        connection: |
          provider: AWS
          region: home
          aws_access_key_id: {{ .accessKey }}
          aws_secret_access_key: {{ .secretKey }}
          aws_signature_version: 4
          host: s3.xmple.io
          endpoint: "https://s3.xmple.io:9000"
          path_style: true
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/s3/minio/root
        property: access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/s3/minio/root
        property: secret_key
