---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly
  labels:
    app.kubernetes.io/name: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: gitlab-gitaly
  storageClassName: longhorn-gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: gitlab-gitaly
  storageClassName: longhorn-gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-master
  labels:
    app.kubernetes.io/name: gitlab
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: gitlab-redis-master
  storageClassName: longhorn-gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-gitlab-redis-master-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: gitlab-redis-master
  storageClassName: longhorn-gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pgsql
  labels:
    app.kubernetes.io/name: gitlab
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: gitlab-pgsql
  storageClassName: longhorn-gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitlab-postgresql-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: gitlab-pgsql
  storageClassName: longhorn-gitlab
