apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-gitaly-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: longhorn-gitaly
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    volumeHandle: gitlab-gitaly-0
    driver: driver.longhorn.io
    fsType: ext4
