apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-{{ .Release.Name }}-gitaly-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: longhorn-gitaly
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: gitlab-gitaly-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-{{ .Release.Name }}-redis-master-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
