apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-object-storage
    template:
      type: Opaque
      data:
        config: |
          s3:
            aws_signature_version: 4
            host: s3.xmple.io
            regionendpoint: "https://s3.xmple.io:9000"
            skipverify: true
            path_style: true
            region: home
            bucket: registry
            accesskey: {{ .accessKey }}
            secretkey: {{ .secretKey }}
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/s3/minio/root
        property: access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/s3/minio/root
        property: secret_key