apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: smtp-password
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/smtp
        property: password
