---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-1
      protocol: HTTPS
      port: 443
      hostname: whoami.xmple.io
      tls:
        certificateRefs:
          - kind: Secret
            name: whoami-tls
    - name: https-2
      protocol: HTTPS
      port: 443
      hostname: whoami2.xmple.io
      tls:
        certificateRefs:
          - kind: Secret
            name: whoami-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-whoami
spec:
  parentRefs:
    - name: whoami-tls
      kind: Gateway
  hostnames:
    - whoami.xmple.io
  rules:
    - matches:
      - path:
          type: Exact
          value: /
      backendRefs:
        - name: whoami
          port: 80
          kind: Service
