apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: whoami-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: web-gw
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: Same