---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: whoami
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: whoami-tls
annotations:
  cert-manager.io/issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: whoami.xmple.io
      tls:
        certificateRefs:
          - kind: Secret
            name: whoami-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-whoami
spec:
  parentRefs:
    - name: whoami
  hostnames:
    - whoami.xmple.io
  rules:
    - matches:
      - path:
          type: Exact
          value: /
      backendRefs:
        - name: whoami
          port: 80
