apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ts
  labels:
    app.kubernetes.io/name: whoami
    tailscale.com/proxy-class: tun-access
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: whoami
      port:
        number: 80
  tls:
    - hosts:
        - whoami-ts