apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: whoami
resources:
  - deployment.yaml
  - service.yaml
  - routes.yaml
  - middleware.yaml