apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: system
  destination:
    namespace: gitlab
    server: {{ .Values.spec.destination.server }}
  source:
    path: gitlab
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin: 
      name: argocd-vault-plugin-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
