---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
spec:
  project: system
  destination:
    namespace: olm
    server: {{ .Values.spec.destination.server }}
  source:
    path: olm
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
