apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: System Project
  sourceRepos:
  - {{ .Values.spec.source.repoURL }}
  - https://prometheus-community.github.io/helm-charts
  destinations:
  - namespace: '*'
    server: {{ .Values.spec.destination.server }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
