---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: system
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 16.6.2
#    helm:
#      values: |

