apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: system
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 16.7.0
    helm:
      values: |
        grafana:
          grafana.ini:
            server:
              #domain: monitor.k3s.xmple.io
              root_url: https://monitor.k3s.xmple.io/grafana
              #serve_from_sub_path: true
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              cert-manager.io/cluster-issuer: letsencrypt-production
            hosts:
            - monitor.k3s.xmple.io
            path: /grafana
            tls:
            - secretName: grafana-tls
              hosts:
              - monitor.k3s.xmple.io
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
