apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: system
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  source:
    path: promtail
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
