apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: system
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.9.1
    helm:
      releaseName: prometheus
      valueFiles:
        - prometheus-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
