---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
spec:
  secretName: grafana-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - monitor.k3s.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`monitor.k3s.xmple.io`) && (PathPrefix(`/grafana`))
    kind: Rule
    services:
    - kind: Service
      name: prometheus-grafana
      port: 80
  tls:
    secretName: grafana-tls
    options:
      name: mintls13
      namespace: traefik