apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authelia
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: network
  hostnames:
    - auth.xmple.io
  rules:
    - backendRefs:
        - name: authelia
          port: 80
          kind: Service
