apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: authelia
spec:
  ingressClassName: cilium
  rules:
    - host: auth.xmple.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 80
  tls:
    - secretName: authelia-tls
      hosts:
        - auth.xmple.io
