apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: authelia
images:
  - name: docker.io/authelia/authelia
    newTag: v4.37.3
resources:
  - redis
  - secret-store.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - pv.yaml
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - users.yaml
      - configuration.yml
