apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: authelia
      app.kubernetes.io/managed-by: ArgoCD
images:
  - name: docker.io/authelia/authelia
    newTag: 4.38.18
resources:
  - redis
  - secret-store.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  #- pv.yaml
  - certificate.yaml
  #- ingress.yaml
  - httproute.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - config/users.yaml
      - config/configuration.yaml
