apiVersion: v1
kind: Secret
metadata:
  name: authelia-external-secrets-token
  annotations:
    kubernetes.io/service-account.name: authelia-external-secrets
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-external-secrets
secrets:
  - name: authelia-external-secrets-token
---  
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.xmple.io:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: authelia
          serviceAccountRef:
            name: authelia-external-secrets
