apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  labels:
    app.kubernetes.io/name: authelia
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: authelia-secrets
  dataFrom:
    - extract:
        key: secret/authelia