apiVersion: v1
kind: Service
metadata:
  name: authelia
  annotations:
    lbipam.cilium.io/sharing-key: bootstrap
    lbipam.cilium.io/sharing-cross-namespace: '*'
spec:
  loadBalancerClass: io.cilium/l2-announcer
  selector:
    app.kubernetes.io/name: authelia
  ports:
    - protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
