apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    namespace: gitea
    server: {{ .Values.spec.destination.server }}
  source:
    path: gitea
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
