apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    namespace: gitlab
    server: {{ .Values.spec.destination.server }}
  source:
    chart: gitlab-operator
    repoURL: https://gitlab.com/api/v4/projects/18899486/packages/helm/stable
    targetRevision: '0.18.3'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
