apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-minecraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    namespace: minecraft
    server: {{ .Values.spec.destination.server }}
  source:
    path: apps
    repoURL: https://github.com/msnelling/minecraft.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
