apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications Project
  sourceRepos:
    - {{ .Values.spec.source.repoURL }}
    - https://charts.gitlab.io/
    - https://gitlab.com/api/v4/projects/18899486/packages/helm/stable
    - https://github.com/msnelling/argocd-db3000.git
    - https://github.com/msnelling/gitops-teslamate.git
  destinations:
    - namespace: '*'
      server: {{ .Values.spec.destination.server }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: cilium.io
      kind: CiliumIdentity
