apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ingress-tls
spec:
  secretName: keycloak-ingress-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - auth.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
