apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.xmple.io`)
      kind: Rule
      services:
        - name: keycloak-discovery
          port: 8080
  tls:
    secretName: keycloak-ingress-tls
    options:
      name: mintls13
      namespace: traefik
