---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgresql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-keycloak
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: keycloak-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: keycloak-postgresql
  storageClassName: longhorn-keycloak
