# Disable etcd monitoring. See https://github.com/cablespaghetti/k3s-monitoring/issues/4
kubeEtcd:
  enabled: false
# Disable kube-controller-manager and kube-scheduler monitoring. See https://github.com/cablespaghetti/k3s-monitoring/issues/2
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

grafana:
  plugins:
    - grafana-piechart-panel
  grafana.ini:
    server:
      domain: monitor.k3s.xmple.io
      root_url: https://monitor.k3s.xmple.io/grafana
      serve_from_sub_path: true
