kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
  
grafana:
  grafana.ini:
    server:
      domain: grafana.k3s.xmple.io
  plugins:
    - grafana-piechart-panel
