gitea:
  gitea:
    config:
      server:
        DOMAIN: gitea.xmple.io
        ROOT_URL: https://gitea.xmple.io/
      database:
        db_type: postgres
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: gitea-postgres-secret
            key: host
      - name: GITEA__DATABASE__NAME
        valueFrom:
          secretKeyRef:
            name: gitea-postgres-secret
            key: database
      - name: GITEA__DATABASE__USER
        valueFrom:
          secretKeyRef:
            name: gitea-postgres-secret
            key: username
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-postgres-secret
            key: password
    admin:
      existingSecret: gitea-admin-secret

  persistence:
    volumeName: gitea-shared-storage
    storageClass: longhorn-gitea

  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  redis-cluster:
    enabled: false