gitea:
  gitea:
    additionalConfigSources:
      - configMap:
          name: gitea-app-ini
      - secret:
          secretName: gitea-app-ini-secret
    admin:
      existingSecret: gitea-admin-secret
    oauth:
      - name: github
        provider: github
        existingSecret: gitea-oauth2-secret

  strategy:
    type: Recreate

  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
    dnsConfig:
      nameservers:
        - 10.1.1.15
        - 10.1.1.20

  persistence:
    volumeName: gitea-shared-storage
    storageClass: longhorn-gitea
    accessModes:
      - ReadWriteMany

  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  valkey-cluster:
    enabled: false

  valkey:
    enabled: true
    global:
      defaultStorageClass: longhorn-gitea
    primary:
      persistence:
        size: 1Gi
