gitea:
  gitea:
    additionalConfigSources:
      - configMap:
          name: gitea-app-ini
      - secret:
          secretName: gitea-app-ini-secret
    admin:
      existingSecret: gitea-admin-secret
    oauth:
      - name: github
        provider: github
        existingSecret: gitea-oauth2-secret

  deployment:
    annotations:
      reloader.stakater.com/auto: "true"

  persistence:
    volumeName: gitea-shared-storage
    storageClass: longhorn-gitea

  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  redis-cluster:
    enabled: false