apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
#resources:
#  - resources/httproute.yaml

helmCharts:
  - name: lgtm-distributed
    repo: https://grafana.github.io/helm-charts
    releaseName: lgtm-distributed
    version: 2.1.0
    #includeCRDs: true
    namespace: monitoring
    valuesFile: lgtm-values.yaml

  - name: alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana-alloy
    version: 1.1.1
    #includeCRDs: true
    namespace: monitoring
    valuesFile: alloy-values.yaml