apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cilium
resources:
  - resources/cilium-gateway.yaml
  - resources/loadbalancer-pools.yaml
  - resources/l2-announcement-policy.yaml