apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: network
resources:
  - resources/cilium-gateway.yaml
  - resources/traefik-gateway.yaml
