apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: https-xmple-io
  hostnames:
    - traefik-gw.xmple.io
  rules:
    - matches:	
        - path:	
            type: PathPrefix	
            value: /
      backendRefs:
        - group: traefik.io
          kind: TraefikService
          name: api@internal
          port: 80
          weight: 1
          