---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
spec:
  parentRefs:
    - name: traefik-gateway
      sectionName: traefik-dashboard
      kind: Gateway
  hostnames:
    - infra.xmple.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /dashboard
    - backendRefs:
        - name: traefik
          port: 9000
          kind: Service
