---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik-lb.xmple.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
          serversTransport: traefik-dashboard-transport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-dashboard-transport
spec:
  serverName: traefik-dashboard
  insecureSkipVerify: true
