apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: promtail-config
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: promtail-config-template
            items:
              - key: promtail.yaml
  data:
    - secretKey: user
      remoteRef:
        key: secret/monitoring/grafana
        property: publisher-user
    - secretKey: apiKey
      remoteRef:
        key: secret/monitoring/grafana
        property: publisher-api-key
