apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccount: promtail
      serviceAccountName: promtail
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Equal
          value: 'true'
      containers:
        - name: promtail-container
          image: grafana/promtail
          imagePullPolicy: Always
          args:
            - -config.file=/etc/promtail/promtail.yaml
          env: 
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
      volumes:
        - name: promtail-config
          secret:
            secretName: promtail-config
