apiVersion: v2
name: gitlab-stack
description: Web-based Git-repository manager
type: application
version: 0.1.0
appVersion: "14.10.0"
dependencies:
  - name: gitlab
    version: 5.10.0
    repository: https://charts.gitlab.io/
