apiVersion: v2
name: gitlab
description: Gitlab Version Control System
type: application
version: 0.1.0
appVersion: "16.5.0"
dependencies:
  - name: gitlab
    version: 7.5.0
    repository: https://charts.gitlab.io
