apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-initial-root-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-initial-root-password
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/install
        property: initial-root-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-postgresql-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-postgresql-password
    template:
      type: Opaque
      data:
        gitlab-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/install
        property: postgresql-postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-github-oauth2
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-github-oauth2
    template:
      type: Opaque
      data:
        provider: |
          name: github
          label: GitHub
          app_id: afddb1a6f0fce00913b8
          app_secret: {{ .githubOauthAppSecret }}
          args:
            scope: user:email
  data:
    - secretKey: githubOauthAppSecret
      remoteRef:
        key: secret/gitlab/install
        property: github-oauth2-app-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-smtp-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-smtp-password
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/gitlab/install
        property: smtp-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-object-storage
    template:
      type: Opaque
      data:
        connection: |
          provider: AWS
          region: home
          aws_access_key_id: {{ .awsAccessKey }}
          aws_secret_access_key: {{ .awsSecretKey }}
          aws_signature_version: 4
          host: s3.xmple.io
          endpoint: "https://s3.xmple.io:9000"
          path_style: true
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: secret/gitlab/install
        property: aws-access-key
    - secretKey: awsSecretKey
      remoteRef:
        key: secret/gitlab/install
        property: aws-secret-key
