apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - secret-store.yaml
  - external-secrets.yaml
  - certificate.yaml
  - storage-class.yaml
  - pv.yaml
  - pvc.yaml
  #- gitlab.yaml

# Until we can get the operator working, we'll use Helm
helmCharts:
- name: gitlab
  includeCRDs: true
  valuesFile: gitlab-values.yaml
  releaseName: gitlab
  version: 6.10.3
  repo: https://charts.gitlab.io