apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: longhorn-gitaly
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    volumeHandle: gitlab-gitaly
    driver: driver.longhorn.io
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-master-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: local-host
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
