apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  volumeName: gitlab-gitaly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-gitlab-redis-master-0
  labels:
    app.kubernetes.io/name: gitlab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
