gitlab:
  global:
    hosts:
      domain: xmple.io
    ingress:
      enabled: true
      configureCertmanager: false
      annotations:
        kubernetes.io/ingress.class: traefik
      tls:
        enabled: true
        secretName: gitlab-tls
    minio:
      enabled: false
    registry:
      bucket: gitlab-registry-storage
    appConfig:
      lfs:
        bucket: gitlab-lfs-storage
        connection:
          secret: object-storage
          key: connection
      artifacts:
        bucket: gitlab-artifacts-storage
        connection:
          secret: object-storage
          key: connection
      uploads:
        bucket: gitlab-uploads-storage
        connection:
          secret: object-storage
          key: connection
      packages:
        bucket: gitlab-packages-storage
        connection:
          secret: object-storage
          key: connection
      backups:
        bucket: gitlab-backup-storage
        tmpBucket: gitlab-tmp-storage
      omniauth:
        enabled: true
        providers:
        - secret: gitlab-github-oauth2
  gitlab:
    gitaly:
      persistence:
        volumeName: gitlab-gitaly
    task-runner:
      enabled: false # Temporarily disabled
      backups:
        objectStorage:
          config:
            secret: s3cmd-config
            key: config
    gitlab-shell:
      service:
        type: LoadBalancer
  registry:
    storage:
      secret: registry-storage
      key: config
  postgresql:
    install: true
    persistence:
      volumeName: gitlab-pgsql
  redis:
    master:
      persistence:
        volumeName: gitlab-redis-master
  gitlab-runner:
    install: false # Temporarily disabled
    runners:
      privileged: true
  nginx-ingress:
    enabled: false
  certmanager:
    install: false
  prometheus:
    install: false
