gitlab:
  # needed for ArgoCD, see https://gitlab.com/gitlab-org/charts/gitlab/-/issues/2979#note_732297487
  upgradeCheck:
    enabled: false 

  # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml
  global:
    hosts:
      domain: xmple.io
    psql:
      host: '10.1.1.30'
      port: 5432
      database: gitlab
      username: gitlab
      password:
        secret: gitlab-postgresql-password
        key: gitlab-password
    ingress:
      enabled: true
      class: traefik
      provider: traefik
      configureCertmanager: false
      tls:
        enabled: true
        secretName: gitlab-tls
    initialRootPassword:
      secret: gitlab-initial-root-password
      key: password
    email:
      from: GitLab@xmple.io
      display_name: "GitLab"
      reply_to: noreply@xmple.io
    smtp:
      enabled: true
      address: smtp.mail.me.com
      port: 587
      starttls_auto: true
      tls: true
      domain: xmple.io
      user_name: masnelling@icloud.com
      password:
        secret: gitlab-smtp-password
        key: password
    minio:
      enabled: false
    registry:
      bucket: gitlab-registry-storage
    kas:
      enabled: true
    appConfig:
      object_store:
        bucket: gitlab-object-storage
        connection:
          secret: gitlab-object-storage
          key: connection
      lfs:
        bucket: gitlab-lfs-storage
        connection:
          secret: gitlab-object-storage
          key: connection
      artifacts:
        bucket: gitlab-artifacts-storage
        connection:
          secret: gitlab-object-storage
          key: connection
      uploads:
        bucket: gitlab-uploads-storage
        connection:
          secret: gitlab-object-storage
          key: connection
      packages:
        bucket: gitlab-packages-storage
        connection:
          secret: gitlab-object-storage
          key: connection
      backups:
        bucket: gitlab-backup-storage
        tmpBucket: gitlab-tmp-storage
      omniauth:
        enabled: true
        providers:
          - secret: gitlab-github-oauth2

  gitlab:
    webservice:
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'      
          cfargotunnel.com/cluster-tunnel: k3s-xmple-io
          cfargotunnel.com/fqdn: gitlab.xmple.io
    gitaly:
      persistence:
        volumeName: gitlab-gitaly
    toolbox:
      backups:
        cron:
          enabled: true
          schedule: 0 1 * * *
          extraArgs: --maximum-backups 7
        objectStorage:
          config:
            secret: gitlab-s3cmd-config
            key: config
    gitlab-shell:
      service:
        type: LoadBalancer
    runner:
      registrationToken:
        secret: gitlab-gitlab-runner-secret
  
  # https://docs.gitlab.com/charts/charts/gitlab/gitlab-runner/
  gitlab-runner:
    gitlabUrl: http://gitlab-webservice-default:8080/
    runners:
      secret: gitlab-gitlab-runner-secret
      privileged: true
      # Runner Configuration
      # https://docs.gitlab.com/runner/configuration/advanced-configuration.html
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{ .Release.Namespace }}"
            image = "ubuntu:22:04"
            dns_policy = "none"
          [runners.kubernetes.dns_config]
            nameservers = ["10.1.1.15"]

  # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/registry/values.yaml
  registry:
    storage:
      secret: gitlab-registry-storage
      key: config

  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  postgresql:
    install: false

  # https://docs.gitlab.com/charts/installation/command-line-options.html#advanced-in-cluster-redis-configuration
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
  redis:
    master:
      persistence:
        volumeName: gitlab-redis-master

  # https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/charts/nginx-ingress
  nginx-ingress:
    enabled: false

  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  certmanager:
    install: false

  # https://docs.gitlab.com/charts/installation/command-line-options.html#prometheus
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
  prometheus:
    install: false