apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: authelia-test
      app.kubernetes.io/managed-by: ArgoCD
resources:
  - secret-store.yaml
  - secrets.yaml
  - certificate.yaml
  - httproute.yaml
configMapGenerator:
  - name: authelia-users
    options:
      disableNameSuffixHash: true
    files:
      - config/users.yaml