---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  labels:
    app.kubernetes.io/name: authelia
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: authelia-secrets
  data:
    - secretKey: storage.encryption.key
      remoteRef: 
        key: authelia
        property: AUTHELIA_STORAGE_ENCRYPTION_KEY
    - secretKey: storage.postgres.password.txt
      remoteRef: 
        key: authelia
        property: AUTHELIA_STORAGE_POSTGRES_PASSWORD
    - secretKey: session.encryption.key
      remoteRef: 
        key: authelia
        property: AUTHELIA_SESSION_SECRET
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef: 
        key: authelia
        property: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
    - secretKey: notifier.smtp.username.txt
      remoteRef: 
        key: authelia
        property: AUTHELIA_NOTIFIER_SMTP_USERNAME
    - secretKey: notifier.smtp.password.txt
      remoteRef: 
        key: authelia
        property: AUTHELIA_NOTIFIER_SMTP_PASSWORD
    - secretKey: configuration.acl.yaml
      remoteRef: 
        key: authelia
        property: acl