apiVersion: v1
kind: Secret
metadata:
  name: argocd-external-secrets-token
  annotations:
    kubernetes.io/service-account.name: argocd-external-secrets
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-external-secrets
secrets:
  - name: argocd-external-secrets-token
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.xmple.io:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: argocd
          serviceAccountRef:
            name: argocd-external-secrets
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
  data:
  - secretKey: dex.github.clientId
    remoteRef: 
      key: github/oauth/argocd
      property: clientId
  - secretKey: dex.github.clientSecret
    remoteRef: 
      key: github/oauth/argocd
      property: clientSecret
