apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: https-xmple-io
  hostnames:
    - argocd.xmple.io
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
          kind: Service
