apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd.git/manifests/cluster-install/?ref=v3.0.9?timeout=90s
  - external-secrets.yaml
  - httproute.yaml
patches:
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
