apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.3.2
resources:
- projects.yaml
- ui-ingress.yaml
- vault-plugin-credentials.yaml
- external-secrets.yaml
patchesStrategicMerge:
- overlays/argocd-repo-server-deploy.yaml
- overlays/argocd-server-deploy.yaml
- overlays/argocd-cm.yaml
- overlays/argocd-rbac-cm.yaml
