apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=v2.12.4
  - projects.yaml
  - ui-ingress.yaml
  - external-secrets.yaml
patches:
  #- path: overlays/argocd-server-deploy.yaml
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
