apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.9
resources:
  - projects.yaml
  - ui-ingress.yaml
  - external-secrets.yaml
patchesStrategicMerge:
  - overlays/argocd-server-deploy.yaml
  - overlays/argocd-cm.yaml
  - overlays/argocd-rbac-cm.yaml
patchesJson6902:
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: helm-values
          secret:
            secretName: helm-values
            optional: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: helm-values
          mountPath: /helm-values
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
