apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.0.3
resources:
- ui-ingress.yaml
- vault-plugin-credentials.yaml
- external-secrets.yaml
patchesStrategicMerge:
- overlays/argocd-repo-server-deploy.yaml
- overlays/argocd-server-deploy.yaml
- overlays/argocd-cm.yaml
- overlays/argocd-rbac-cm.yaml
