apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=v2.14.1
  - external-secrets.yaml
  - httproute.yaml
patches:
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
