apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=v2.12.1
  - projects.yaml
  - ui-ingress.yaml
  - external-secrets.yaml
patches:
  - path: overlays/argocd-server-deploy.yaml
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: helm-values
          secret:
            secretName: helm-values
            optional: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: helm-values
          mountPath: /helm-values
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
