apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bootstrap Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: cilium.io
      kind: CiliumIdentity
