apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bootstrap Project
  sourceRepos:
  - https://github.com/msnelling/argocd-bootstrap.git
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
  - https://helm.releases.hashicorp.com
  - https://charts.jetstack.io
  - https://charts.longhorn.io
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
