---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  secretName: argocd-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - argocd.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  ingressClassName: cilium
  rules:
    - host: argocd.xmple.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
  tls:
    - secretName: argocd-tls
      hosts:
        - argocd.xmple.io
