kind: Secret
apiVersion: v1
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: secret/data/cert-manager/letsencrypt/cloudflare
type: Opaque
data:
  email: <email | base64encode>
  api-token: <api_token | base64encode>
