apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  annotations:
    avp.kubernetes.io/path: secret/data/k3s/cloudflare/cert-manager/issuer
type: Opaque
data:
  api-token: <api-token | base64encode>
