---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
spec:
  secretName: grafana-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - grafana.k3s.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mintls13
  labels:
    app.kubernetes.io/name: teslamate
spec:
  minVersion: VersionTLS13
  curvePreferences:
    - CurveP384
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.k3s.xmple.io`)
      kind: Rule
      services:
        - kind: Service
          name: prometheus-grafana
          port: 80
  tls:
    secretName: grafana-tls
    options:
      name: mintls13
