apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: operator-oauth
    template:
      type: Opaque
      data:
        client_id: "{{ .oauthClientId }}"
        client_secret: "{{ .oauthClientSecret }}"
  data:
    - secretKey: oauthClientId
      remoteRef:
        key: secret/tailscale/oauth/homelab
        property: id
    - secretKey: oauthClientSecret
      remoteRef:
        key: secret/tailscale/oauth/homelab
        property: secret
