---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-dashboard-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-dashboard-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - longhorn.k3s.xmple.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.k3s.xmple.io`)
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-dashboard-tls
    options:
      name: mintls13
      namespace: traefik
