---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-dashboard-tls
spec:
  secretName: longhorn-dashboard-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - longhorn.k3s.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mintls13
  labels:
    app.kubernetes.io/name: longhorn
spec:
  minVersion: VersionTLS13
  curvePreferences:
    - CurveP384
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  labels:
    app.kubernetes.io/name: longhorn
spec:
  forwardAuth:
    address: http://authelia.authelia.svc.cluster.local/api/verify?rd=https%3A%2F%2Fauth.xmple.io%2F
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: longhorn-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.k3s.xmple.io`)
      services:
        - name: longhorn-frontend
          port: 80
      #middlewares:
      #  - name: forwardauth-authelia
  tls:
    secretName: longhorn-dashboard-tls
    options:
      name: mintls13
