kind: Secret
apiVersion: v1
metadata:
  name: s3-secret
  annotations:
    avp.kubernetes.io/path: secret/data/s3/minio/root
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <access_key | base64encode>
  AWS_SECRET_ACCESS_KEY: <secret_key | base64encode>
  AWS_ENDPOINTS: <endpoint | base64encode>
