apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: s3-secret
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .s3.access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3.secret_key }}"
        AWS_ENDPOINTS: "{{ .s3.endpoint }}"
  data:
    - secretKey: s3
      remoteRef:
        key: secret/k3s/s3/minio/root
