apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: s3-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ `{{ .accessKey }}` }}"     # We need to escape like this when used in helm charts
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .secretKey }}` }}"
        AWS_ENDPOINTS: "{{ `{{ .endpoint }}` }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/s3/minio/root
        property: access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/s3/minio/root
        property: secret_key
    - secretKey: endpoint
      remoteRef:
        key: secret/s3/minio/root
        property: endpoint
