apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflare-tunnel
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloudflared
          image: docker.io/cloudflare/cloudflared:latest
          imagePullPolicy: Always
          args:
            - tunnel
            - --no-autoupdate
            - run
          envFrom:
            - secretRef:
                name: cloudflare-tunnel
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 50Mi
