apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudflare-tunnel
    template:
      type: Opaque
      data:
        TUNNEL_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/talos/cloudflare/tunnel
        property: tunnel-token
