apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xmple-io-tls
spec:
  secretName: xmple-io-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - "*.xmple.io"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
