---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-gateway
spec:
  blocks:
    - start: "10.1.1.50"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: network
      io.kubernetes.service.name: cilium-gateway-cilium-gateway-tls
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-gateway
spec:
  blocks:
    - start: "10.1.1.51"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: network
      io.kubernetes.service.name: traefik-gateway-traefik-gateway-tls
