---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-lb
spec:
  blocks:
    - start: "10.1.1.48"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: traefik
      io.kubernetes.service.name: traefik
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-gw
spec:
  blocks:
    - start: "10.1.1.51"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: traefik
      io.kubernetes.service.name: traefik-gateway
