theme: dark
default_2fa_method: webauthn

server:
  address: tcp://:9091/

log:
  level: info

telemetry:
  metrics:
    enabled: false

totp:
  disable: false

webauthn:
  disable: false
  enable_passkey_login: true
  display_name: 'Authelia'

identity_validation:
  reset_password:
    jwt_secret: 'supplied by vault'

authentication_backend:
  password_reset:
    disable: false
  file:
    path: /config/users.yaml

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ''

access_control:
  default_policy: deny
  rules:
    - domain: db3000.xmple.io
      subject: group:db3000
      policy: one_factor
    - domain: '*.xmple.io'
      subject: group:admin
      policy: two_factor

session:
  secret: 'supplied by vault'
  cookies:
    - name: 'authelia_session'
      domain: xmple.io
      authelia_url: https://auth.xmple.io
      default_redirection_url: https://home.xmple.io

  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

  redis:
    host: redis
    port: 6379
    database_index: 0

storage:
  postgres:
    address: 'tcp://10.1.1.30:5432'
    database: 'authelia'
    username: 'authelia'
    password: 'supplied by vault'

notifier:
  disable_startup_check: false
  smtp:
    address: smtp://smtp.mail.me.com:587
    username: 'supplied by vault'
    password: 'supplied by vault'
    sender: 'Authelia <noreply@xmple.io>'
    subject: '[Authelia] {title}'
