users:
  mark:
    disabled: false
    displayname: Mark Snelling
    email: mark@bakedbeans.com
    password: "$argon2id$v=19$m=65536,t=3,p=4$qTj7LHiWYtphz+ZCdl5O/A$f+jDjmWg7eKT3I2X0q7EY+HFH3gAC7RZJJQe514z/ZE"
    groups:
      - admin
      - db3000
  mike:
    disabled: false
    displayname: Mike
    email: clamber.dine-4w@icloud.com
    password: "$argon2id$v=19$m=65536,t=3,p=4$rt5cibZgMJLRSs+irdvhvA$odLl0sfGcKtus5sx/bIqw0iL7VHVYBddvHUp63Y0Qeg"
    groups:
      - admin
      - db3000
