apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini
data:
  server: |
    DOMAIN=gitea.xmple.io
    ROOT_URL=https://gitea.xmple.io/
    SSH_DOMAIN=gitea.xmple.io
  service: |
    DISABLE_REGISTRATION=true
  migrations: |
    ALLOWED_DOMAINS=github.com,*.github.com
  oauth2_client: |
    ACCOUNT_LINKING=login
  mailer: |
    ENABLED=true
    SMTP_ADDR=smtp.mail.me.com
    SMTP_PORT=587
    PROTOCOL=smtp+starttls
    FROM="Gitea" <noreply@xmple.io>
  ssh.minimum_key_sizes: |
    RSA=2048
  actions: |
    ENABLED=true
    DEFAULT_ACTIONS_URL=github
    STORAGE_TYPE=minio
    LOG_RETENTION_DAYS=30
    ARTIFACT_RETENTION_DAYS=30
  storage_minio: |
    MINIO_ENDPOINT=s3.xmple.io:9001
