---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgres-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-postgres-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/admin
