---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgres-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-postgres-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oauth2-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-oauth2-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/oauth2/github
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-app-ini-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-app-ini-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        database: |
          DB_TYPE=postgres
          HOST={{ printf "{{ .host }}" }}
          NAME={{ printf "{{ .database }}" }}
          USER={{ printf "{{ .username }}" }}
          PASSWD={{ printf "{{ .password }}" }}
  dataFrom:
    - extract:
        key: secret/gitea/database
