---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgres-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-postgres-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oauth2-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-oauth2-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/gitea/oauth2/github
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-app-ini-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-app-ini-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        security: |
          SECRET_KEY='{{ printf "{{ .config.secretKey }}" }}'
        database: |
          DB_TYPE='postgres'
          HOST='{{ printf "{{ .database.host }}" }}'
          NAME='{{ printf "{{ .database.database }}" }}'
          USER='{{ printf "{{ .database.username }}" }}'
          PASSWD='{{ printf "{{ .database.password }}" }}'
        mailer: |
          USERNAME='{{ printf "{{ .smtp.username }}" }}'
          PASSWORD='{{ printf "{{ .smtp.password }}" }}'
  data:
    - secretKey: config
      remoteRef:
        key: secret/gitea/config
    - secretKey: database
      remoteRef:
        key: secret/gitea/database
    - secretKey: smtp
      remoteRef:
        key: secret/gitea/smtp
