---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-gitea
provisioner: driver.longhorn.io
reclaimPolicy: Retian
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  fsType: ext4
  numberOfReplicas: "2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-shared-storage
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: longhorn-gitea
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    volumeHandle: gitea-shared-storage
    driver: driver.longhorn.io
    fsType: ext4
