apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-external-secrets
secrets:
  - name: gitea-external-secrets-token
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-external-secrets-token
  annotations:
    kubernetes.io/service-account.name: gitea-external-secrets
type: kubernetes.io/service-account-token
