apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/component: promtail
  app.kubernetes.io/part-of: grafana
  app.kubernetes.io/managed-by: argocd
resources:
  - resources/config_template.yaml
  - resources/secret_store.yaml
  - resources/config_secret.yaml
  - resources/service_account.yaml
  - resources/cluster_role.yaml
  - resources/cluster_role_binding.yaml
  - resources/daemonset.yaml
